---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osiris-scheduler.name" . }}-cm
  labels:
    type: {{ .Values.global.type }}
    name: {{ .Values.global.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.workflowTemplate.configPath | base }}: |
{{ (tpl (.Files.Get "files/conf.ini") . ) | indent 4 }}
{{ .Values.config | indent 4 }}
{{ toYaml .Values.configFiles | nindent 2 }}
