---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ template "osiris-scheduler.name" . }}-es
  labels:
    type: {{ .Values.global.type }}
    name: {{ .Values.global.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  refreshInterval: {{ .refreshInterval | default "1m" | quote }}
  secretStoreRef:
    name: {{ template "osiris-scheduler.name" . }}-ss
    kind: SecretStore

  dataFrom:
    - key: credentials

  target:
    name: {{ template "osiris-scheduler.name" . }}-secrets
    template:
      data:
{{ .Values.secrets.secretTemplate | toYaml | indent 8 }}
