---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ template "osiris-scheduler.name" . }}-es
  labels:
    type: {{ .Values.global.type }}
    name: {{ .Values.global.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  refreshInterval: {{ .refreshInterval | default "1m" | quote }}
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  data:
    - secretKey: clientId
      remoteRef:
        key: credentials
        property: client_id
    - secretKey: clientSecret
      remoteRef:
        key: credentials
        property: secret
    - secretKey: tenantId
      remoteRef:
        key: credentials
        property: tenant_id

  target:
    name: app-secrets
    template:
      data:
      # https://external-secrets.io/guides-templating/
        credentials.ini: |
          [Authorization]
          tenant_id = {{`{{ .tenantId | toString }}`}}
          client_id = {{`{{ .clientId | toString }}`}}
          client_secret = {{`{{ .clientSecret | toString }}`}}
