---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ template "osiris-scheduler.name" . }}-ss
  labels:
    type: {{ .Values.global.type }}
    name: {{ .Values.global.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  provider:
    vault:
      server: "{{ .Values.secrets.secretServer }}"
      path: "{{ .Values.secrets.secretName }}-authentication"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: {{ .Values.secrets.mountPath }}
          # A required field containing the Vault Role to assume.
          role: "{{ .Values.secrets.secretName }}-authentication-reader"
