apiVersion: v2
name: drill
version: 0.1.20
description: Helm Charts for deploying Apache Drill Clusters on Kubernetes
type: application
home: 'http://drill.apache.org/'

maintainers:
  - name: MadsHT

dependencies:
- name: lethe
  version: "0.1.4"
  repository: https://open-olympus-project.github.io/repo-helm/
  condition: lethe.enabled
- name: janus
  version: "0.1.4"
  repository: https://open-olympus-project.github.io/repo-helm/
  condition: janus.enabled
- name: zookeeper
  version: 0.1.5
  repository: 'https://open-dataplatform.github.io/osiris-helm/'
