kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zk-rb
subjects:
  - kind: ServiceAccount
    name: zk-sa
roleRef:
  kind: Role
  name: zk-role
  apiGroup: rbac.authorization.k8s.io

