apiVersion: v1
kind: Service
metadata:
  name: {{.Values.drill.id}}-web-svc
  labels:
    app: {{.Values.drill.id}}-web-svc
spec:
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.drill.httpPort }}
    targetPort: {{ .Values.drill.httpPort }}
  - protocol: TCP
    name: server
    port: {{ .Values.drill.userServerPort }}
    targetPort: {{ .Values.drill.userServerPort }}
  type: {{ .Values.drill.serviceType }}
  selector:
    app: drill-app
