---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drill-es-tpl-cm
data:
{{- range $path, $_ :=  .Files.Glob  "conf/*" }}
  {{ $path | replace "files/" "" }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}