kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drill-rb
subjects:
  - kind: ServiceAccount
    name: drill-sa
roleRef:
  kind: Role
  name: drill-role
  apiGroup: rbac.authorization.k8s.io

