apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.drill.id}}-drillbit
spec:
  serviceName: drill-service
  replicas: {{.Values.drill.count}}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: drill-app
  template:
    metadata:
      labels:
        app: drill-app
    spec:
{{- with .Values.drill.imagePullSecrets }}
      imagePullSecrets:
{{ . | toYaml | indent 10 }}
{{- end }}
      affinity:
{{- with .Values.drill.nodeSelectorTerms }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
{{ . | toYaml | indent 14}}
{{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - drill-app
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: drill-sa
      containers:
        - name: drill-pod
          imagePullPolicy: {{ .Values.drill.imagePullPolicy }}
          image: {{.Values.drill.image}}
          ports:
            - containerPort: {{ .Values.drill.httpPort }}
              name: http
            - containerPort: {{ .Values.drill.userServerPort }}
              name: userport
            - containerPort: {{ add .Values.drill.userServerPort 1 }}
              name: controlport
            - containerPort: {{ add .Values.drill.userServerPort 2 }}
              name: dataport
          env:
            - name: KUBERNETES_CONTAINER
              value: "true"
            - name: POD_NAME
              value: "drill-bit"
            - name: DRILL_ZK_ROOT
              value: {{.Values.drill.id}}
            - name: ZK_HOST
              value: "zk-0.zk-service.apache-drill.svc.cluster.local"
            - name: ZK_PORT
              value: "2181"
            - name: DRILL_HEAP
              value: {{.Values.drill.heapMemory}}
            - name: DRILL_MAX_DIRECT_MEMORY
              value: {{.Values.drill.directMemory}}
            - name: DRILL_HTTP_PORT
              value: "{{.Values.drill.httpPort}}"
            - name: DRILL_USER_SERVER_PORT
              value: "{{.Values.drill.userServerPort}}"
          livenessProbe:
            exec:
              command:
              {{- range .Values.drill.livenessProbe.exec.command }}
                - {{ . | quote }}
              {{- end }}
            initialDelaySeconds: {{ .Values.drill.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.drill.livenessProbe.periodSeconds }}
            timeoutSeconds:  {{ .Values.drill.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.drill.livenessProbe.failureThreshold }}
          readinessProbe:
            exec:
              command:
              {{- range .Values.drill.readinessProbe.exec.command }}
              - {{ . | quote }}
              {{- end }}
            initialDelaySeconds: {{ .Values.drill.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.drill.readinessProbe.periodSeconds }}
            timeoutSeconds:  {{ .Values.drill.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.drill.readinessProbe.failureThreshold }}
          lifecycle:
            preStop:
              exec:
                command:
                  {{- range .Values.drill.lifecycle.preStop.exec.command }}
                  - {{ . | quote }}
                  {{- end }}
          {{- with .Values.drill.volumeMounts }}
          volumeMounts:
{{ . | toYaml | indent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.drill.terminationGracePeriodSeconds }}
      {{- with .Values.drill.volumes }}
      volumes:
{{ . | toYaml | indent 8 }}
      {{- end }}
      initContainers:
        - name: zk-available
          image: busybox
          command: ['sh', '-c', 'until nc -z zk-service 2181; do echo Waiting for ZK to come up; sleep 5; done; ']
