---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-cm
  labels:
    app: {{ .Values.global.app }}
    transformation: {{ .Values.global.transformation }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- toYaml .Values.config | nindent 2 }}